INSERT INTO CUSTOMER ("CID","CNAME","CSURENAME","CSTREET","CNUMBER","CPCODE","CSTATE","CCOUNTRY","CDEALERID") VALUES (1,'EISELE','MARKUS','Werner-von-Siemens','7 C','96584','Bavaria','Germany',1)
INSERT INTO CUSTOMER ("CID","CNAME","CSURENAME","CSTREET","CNUMBER","CPCODE","CSTATE","CCOUNTRY","CDEALERID") VALUES (2,'EISELE','MARKUS','Werner-von-Siemens','7 C','96584','Bavaria','Germany',2)
INSERT INTO CSEQUENCE ("ID", "VALUE") VALUES ('Customer',1)
